#!/bin/bash
ssh-keygen -t rsa
ssh-copy-id -i ~/.ssh/id_rsa root@192.168.1.20
ssh-copy-id -i ~/.ssh/id_rsa root@192.168.1.24
ssh-copy-id -i ~/.ssh/id_rsa root@192.168.1.25
ssh-copy-id -i ~/.ssh/id_rsa root@192.168.1.26
ansible-playbook webserver.yaml -i hosts.ini
curl 192.168.1.20
curl 192.168.1.24
curl 192.168.1.25
curl 192.168.1.26
